### ISSUE TITLE
LuaJIT 2.0 doesn't support ARM64 architecture

### ISSUE THREAD

**Issue by istiak101** [litespeedtech/third-party#3]
LuaJIT 2.0 doesn't support ARM64 architecture but 2.1 development branch has support for ARM64.

https://github.com/LuaJIT/LuaJIT/blob/v2.0/src/lj_arch.h
https://github.com/LuaJIT/LuaJIT/blob/v2.1/src/lj_arch.h

Will you build LuaJIT from 2.1 branch for ARM64 or remove LuaJIT build in case of ARM64 architecture?
https://github.com/litespeedtech/third-party/blob/master/script/build_ols.sh

OLS build script error log.
https://files.istiak.com/ols/luajit.txt

**Comment by litespeedtech** [comment]
Lua support is optional, and mod_lua is coded with LuaJIT 2.0, may not work with 2.1 .

**Comment by kalleboy** [comment]
How to not install modules like ModSecurity, BoringSSL and Luajit during installation? Is there any way to customize the modules to build? Is there any option to prevent their installation?

Thanks.
